version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: elasticsearch
    volumes:
      - ${ES_DATA_DIR}:/usr/share/elasticsearch/data
    ports:
      - ${ES_PORT}:9200
    restart: always
    # environment:
    #   - xpack.security.enabled=false
    #   - discovery.type=single-node
    environment:
      [
        "CLI_JAVA_OPTS=-Xms2g -Xmx2g",
        "bootstrap.memory_lock=true",
        "discovery.type=single-node",
        "xpack.security.enabled=false",
        "xpack.security.enrollment.enabled=false",
      ]
    networks:
      - elastic-internal
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          cpus: "2.0"
        reservations:
          cpus: "1.0"

  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    container_name: kibana
    volumes:
      - ${KIBANA_DATA_DIR}:/usr/share/kibana/data
    ports:
      - ${KIBANA_PORT}:5601
    networks:
      - elastic-internal
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      # XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: d1a66dfd-c4d3-4a0a-8290-2abcb83ab3aa
    deploy:
      resources:
        limits:
          cpus: "2.0"
        reservations:
          cpus: "1.0"

networks:
  elastic-internal:
    name: elastic-internal
